### ISSUE TITLE
After successful registration, add the text "Email send" and tell the user to look inside the spam if the email is not in the inbox.

### ISSUE THREAD

**Issue by bsaptyadeep** [waltz-001/waltz-client#27]
**Describe the bug**
After successful registration, add the text "Email send" and tell the user to look inside the spam if the email is not in the inbox.

**To Reproduce**
1. Register Now.
2. complete the form correctly

**Expected behavior**
Users do not know what to do if the email is not in the inbox.

**Bug found in Mobile or Web?**
Both web and Mobile

**Comment by Soumajith** [comment]
Done
