### ISSUE TITLE
Add social Media links to the website footer

### ISSUE THREAD

**Issue by bsaptyadeep** [waltz-001/waltz-client#28]
Facebook: https://www.facebook.com/waltz.uit
Instagram: https://instagram.com/waltz.uitbu?igshid=YmMyMTA2M2Y=

**Comment by giri-madhan** [comment]
Hi, can I work on this issue?

**Comment by bsaptyadeep** [comment]
Sorry brother but right now we are accepting Pull requests only from our college students. Have a good day :)

**Comment by giri-madhan** [comment]
That's alright. Good luck!

**Comment by Soumajith** [comment]
Done
