### ISSUE TITLE
Image cards in event section needs some gaping between them.

### ISSUE THREAD

**Issue by Dona4449** [waltz-001/waltz-client#37]
Then Image cards doesn't have any gap between them. The images also needs to be aligned properly in the box.

![image](https://user-images.githubusercontent.com/90026837/235836557-e1d14efd-d973-47f8-b385-a7d061327fc2.png)

**Comment by Sky-De** [comment]
It can be fixed easily
Please assign this to me
I will fix all as soon as i get assignments
Thanks

**Comment by The15thSin** [comment]
This bug was fixed in when the Detailed Events page was made.
