### ISSUE TITLE
Gap between View Details and Register button.

### ISSUE THREAD

**Issue by The15thSin** [waltz-001/waltz-client#65]
**Describe the bug**
The Gap between **Register** and **View Details** buttons is very much in MOBILE VIEW. 

**To Reproduce**
Just open the Landing page on phone, it will be clearly visible.

**Expected behavior**
The Gap between both buttons should be **reduced**.

**Screenshots**
![Screenshot_2023-05-11-17-50-51-91_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/waltz-001/waltz-client/assets/90421936/d21255db-f1ef-4dbb-91d0-4d811313bf59)

**Bug found in Mobile or Web?**
**MOBILE VIEW**

**Additional context**
None

**Comment by giri-madhan** [comment]
Hi @The15thSin , I could fix this issue. Could you please assign this task to me?
